### ISSUE TITLE
Add favicon to your browser

### ISSUE THREAD

**Issue by sangjunp4rk** [CatsEyeDjinn/Colmar-Academy#4]
Don't forget to put a favicon! This is the small icon on your browser tab. You can add `<link rel="icon" href="http://example.com/favicon.png">` to you `<head>` element.

https://github.com/CatsEyeDjinn/Colmar-Academy/blob/master/index.html#L3

**Comment by CatsEyeDjinn** [comment]
Ill keep this is mind, the icon gave me a lot of trouble. Thank you!
